- name: Todo Web Servers
  hosts: webservers
  remote_user: ec2-user

  vars_prompt:
  - name: trello_api_key
    prompt: What is your Trello API Key?

  - name: trello_api_token
    prompt: What is your Trello API Token?
	
  tasks:
  - name: Install Git
    ansible.builtin.yum:
      name: git
      state: latest
    become: yes

  - name: Install Python 3.11
    ansible.builtin.yum:
      name: python311
      state: latest
    become: yes

  - name: Install Python Poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
    args:
      creates: /home/ec2-user/.local/bin/poetry

  - name: Create WebApp Folder
    ansible.builtin.shell: mkdir /opt/todoapp
    args:
      creates: /opt/todoapp
    become: yes

  - name: Set WebApp Folder permissions
    ansible.builtin.shell: chown ec2-user /opt/todoapp
    become: yes

  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/StuShepherdUK/DevOps-Course-Starter.git'
      dest: /opt/todo
      version: module_4