name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the docker image
      run: docker build --target test --tag todo-app:test .

    - name: Run the docker test image
      run:  docker run -p 5000:5000 --env-file .env.test todo-app:test

  push_to_prod:
    name: Push To Production
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - name: Publish
      run: echo Publishing!